# Generated by Django 3.0.6 on 2020-06-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroname', models.CharField(max_length=100)),
                ('heroage', models.IntegerField(default=25)),
                ('herogender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('herorole', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Horror', 'Horror'), ('Romance', 'Romance')], max_length=40)),
                ('herofilmcount', models.IntegerField(default=0)),
                ('heroemail', models.EmailField(max_length=100)),
            ],
        ),
    ]
