# Generated by Django 3.0.6 on 2020-06-12 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tollywood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heroregister',
            old_name='herorole',
            new_name='heroroles',
        ),
    ]
