# Generated by Django 3.0.6 on 2020-06-13 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tollywood', '0002_auto_20200612_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroregister',
            name='heroimage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='hero_profiles/'),
            preserve_default=False,
        ),
    ]
