# Generated by Django 3.0.6 on 2020-06-13 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tollywood', '0003_heroregister_heroimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroregister',
            name='heroautograph',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='hero_autographs/'),
            preserve_default=False,
        ),
    ]
