# Generated by Django 3.0.6 on 2020-06-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tollywood', '0006_auto_20200615_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=100),
        ),
    ]
