# Generated by Django 3.0.6 on 2020-06-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StuName', models.CharField(max_length=100)),
                ('StuAge', models.IntegerField()),
                ('StuEmail', models.EmailField(max_length=100)),
                ('StuRoll', models.CharField(max_length=20)),
            ],
        ),
    ]
