# Generated by Django 3.0.6 on 2020-06-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacName', models.CharField(max_length=100)),
                ('FacAge', models.IntegerField()),
                ('FacEmail', models.EmailField(max_length=100)),
                ('FacID', models.CharField(max_length=20)),
            ],
        ),
    ]
