# Generated by Django 3.0.6 on 2020-06-08 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_facultydata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacultyData',
        ),
    ]
