# Generated by Django 3.0.6 on 2020-06-09 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_facultydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsdata',
            name='StuPassword',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
