# Generated by Django 3.0.6 on 2020-06-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_studentsdata_stupassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(max_length=100)),
                ('LName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Mobile', models.IntegerField()),
                ('Gender', models.CharField(max_length=6)),
            ],
        ),
    ]
